# Generated by Django 4.2.21 on 2024-08-01 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReminderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_expiration_enabled', models.BooleanField(default=True, help_text='Send reminders for quote expirations')),
                ('quote_expiration_timing', models.CharField(choices=[('1_day', '1 Day'), ('3_days', '3 Days'), ('7_days', '7 Days'), ('14_days', '14 Days')], default='3_days', help_text='When to send quote expiration reminders', max_length=20)),
                ('invoice_due_enabled', models.BooleanField(default=True, help_text='Send reminders for invoice due dates')),
                ('invoice_due_timings', models.JSONField(default=list, help_text='List of timing options for invoice due date reminders (e.g., [\'3_days\', \'1_day\'])')),
                ('invoice_overdue_enabled', models.BooleanField(default=True, help_text='Send reminders for overdue invoices')),
                ('invoice_overdue_interval', models.IntegerField(default=3, help_text='Days between overdue reminders (0 for no recurring reminders)')),
                ('email_address', models.EmailField(help_text="Email address to send reminders to (defaults to user's email)", max_length=254)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='User these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='email_reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Reminder Settings',
                'verbose_name_plural': 'Email Reminder Settings',
                'db_table': 'reminders_settings',
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('quote_expiration', 'Quote Expiration'), ('invoice_due', 'Invoice Due Date'), ('invoice_overdue', 'Invoice Overdue')], help_text='Type of reminder this template is for', max_length=20)),
                ('subject_template', models.CharField(help_text='Template for email subject (supports placeholders)', max_length=200)),
                ('body_template', models.TextField(help_text='Template for email body (supports placeholders)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User this template belongs to (null for system default)', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Template',
                'verbose_name_plural': 'Reminder Templates',
                'db_table': 'reminders_templates',
                'unique_together': {('user', 'reminder_type')},
            },
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('quote_expiration', 'Quote Expiration'), ('invoice_due', 'Invoice Due Date'), ('invoice_overdue', 'Invoice Overdue')], help_text='Type of reminder sent', max_length=20)),
                ('content_type', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], help_text='Type of content this reminder is for', max_length=20)),
                ('object_id', models.UUIDField(help_text='ID of the quote or invoice')),
                ('subject', models.CharField(help_text='Email subject', max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(help_text='When this reminder was originally scheduled for')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User this reminder was sent to', on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent Reminder',
                'verbose_name_plural': 'Sent Reminders',
                'db_table': 'reminders_sent',
                'ordering': ['-sent_at'],
                'unique_together': {('user', 'content_type', 'object_id', 'reminder_type', 'scheduled_for')},
            },
        ),
    ]