# Generated by Django 4.2.21 on 2025-08-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_enhance_client_model"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="client",
            name="unique_client_email_per_owner",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_owner_i_ae608d_idx",
            old_name="clients_cli_owner_i_aacf3f_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_owner_i_b9a90f_idx",
            old_name="clients_cli_owner_i_8c8cc3_idx",
        ),
        migrations.RenameIndex(
            model_name="client",
            new_name="clients_cli_owner_i_5172d5_idx",
            old_name="clients_cli_owner_i_d72e7e_idx",
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("owner", "email"),
                name="unique_client_email_per_owner",
            ),
        ),
    ]
