# Generated by Django 4.2.21 on 2025-08-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0002_enhance_invoicing_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_owner_i_eedb7c_idx",
            old_name="invoicing_in_owner_i_4a9b5c_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_owner_i_88c591_idx",
            old_name="invoicing_in_owner_i_2e8f7d_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_owner_i_52a534_idx",
            old_name="invoicing_in_owner_i_f6a9c4_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoicing_i_due_dat_92e42f_idx",
            old_name="invoicing_in_due_dat_1b5e7a_idx",
        ),
        migrations.RenameIndex(
            model_name="invoicelineitem",
            new_name="invoicing_i_invoice_a00ace_idx",
            old_name="invoicing_in_invoice_8d3f5e_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="invoicing_i_owner_i_b7ac47_idx",
            old_name="invoicing_it_owner_i_b26eda_idx",
        ),
        migrations.RenameIndex(
            model_name="item",
            new_name="invoicing_i_owner_i_c94fc0_idx",
            old_name="invoicing_it_owner_i_e9a4c6_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="invoicing_q_owner_i_89b4c6_idx",
            old_name="invoicing_qu_owner_i_6f4e99_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="invoicing_q_owner_i_aa93e8_idx",
            old_name="invoicing_qu_owner_i_8a7b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="invoicing_q_owner_i_e1d707_idx",
            old_name="invoicing_qu_owner_i_d5f7a2_idx",
        ),
        migrations.RenameIndex(
            model_name="quote",
            new_name="invoicing_q_valid_u_ecf7d0_idx",
            old_name="invoicing_qu_valid_u_9e4b6f_idx",
        ),
        migrations.RenameIndex(
            model_name="quotelineitem",
            new_name="invoicing_q_quote_i_126b12_idx",
            old_name="invoicing_qu_quote_i_c7d8e5_idx",
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="quote",
            unique_together=set(),
        ),
    ]
